### ISSUE TITLE
Vendored Dependencies use outdated @actions/core

### ISSUE THREAD

**Issue by rymndhng** [DeLaGuardo/setup-clj-kondo#7]
Hey there! 

Would it be possible to create a new release?a

I noticed that this PR didn't have the intended effect: https://github.com/DeLaGuardo/setup-clj-kondo/pull/6

The vendored dependencies still point to an old version of `@actions/core`

**Comment by DeLaGuardo** [comment]
Thanks for letting me know. I will update ASAP

**Comment by DeLaGuardo** [comment]
fixed in master, please use `DeLaGuardo/setup-clj-kondo@master` version in your actions

**Comment by rymndhng** [comment]
Thank you! Works like a charm ;)
